### PR TITLE
Restore values changed to aliases by iterator (OrderedDictionary.Enumerator.CurrentValueAliased)

### PR DESCRIPTION
**Pull request by crbrz**
Fix for #345

### CODE REVIEW

**Comment by jakubmisek** [comment]
sadly, this is extremely performance+memory critical implementation,
`Dispose` is not guaranteed to be called,
`PhpAlias` already has `ReferenceCount` for these purposes ready.

This would have to be tightly integrated into all APIs and compiler in order to work properly

**Comment by crbrz** [comment]
It's more of a workaround, each `foreach` loop that uses a reference variable to access the values exposes the array to unwanted changes (values in array are changed to `PhpAlias` when `Enumerator.CurrentValueAliased` property is accessed even if no changes are made to the value) which can lead to weird runtime bugs. Basically, with current implementation the PHP sources must be patched to avoid any `foreach` loops with reference variables for current value access.

From what I understand to change a value directly in the array, the code generated for `foreach` loops should use something like a property on the enumerator that returns a `ref PhpValue` to the current value in the array data but this means the compiler must know how to use that enumerator property in other expressions where the current value variable might show up.

**Comment by jakubmisek** [comment]
It is more than that. The workaround introduces set of new issues. E.g. If you'd use any of variables inside the `foreach` loop by reference it would change them back to values.

The issue #345 is a sad side effect of PHP's reference counting, one quick fix always introduces another issue. Important to note; the issue is not about `foreach` at all - it is about reference counting in general. The `foreach` just makes use of it.

**Comment by crbrz** [comment]
Even if no other variables are created by reference from `foreach` loop, the variable used to access the values by reference lives until the function/script finishes (I completely forgot about this).

I guess it's patching PHP sources where necessary until `PhpAlias` gets reference counting implemented. Btw, I noticed the changes in this commit [WORKAROUND: avoid aliasing $endpoints elements](https://github.com/iolevel/wpdotnet-sdk/commit/c030eb97552b7598de56129edf2fbbac7a72667d) were overwritten when WordPress was updated.

**Comment by bfistein** [comment]
You're right @crbrz, happened in a previous PR and we didn't notice. Thanks a lot for your contributions!

**Comment by jakubmisek** [comment]
fixed in compiler in https://github.com/peachpiecompiler/peachpie/commit/56f591c9ef733dd4f5865e6528bbe308ad726cfa

**Pull request closed without merging**
