### PR TITLE
To build on .NET 6.0

### PR DESCRIPTION
**Pull request by jee-mj**
I worked to try to get the WordPress plugin running on .NET 6.0, but ran into issues because I do not have a custom NUGET repo setup. Just wanted to share this ASAP. I have it building correctly, I think.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/peachpiecompiler/peachpie?pullRequest=1097) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/peachpiecompiler/peachpie?pullRequest=1097) before we can accept your contribution.<br/><br/>:x: jee-mj [sign now](https://cla.dotnetfoundation.org/peachpiecompiler/peachpie?pullRequest=1097)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/peachpiecompiler/peachpie?pullRequest=1097) it.</sub>

**Comment by jee-mj** [comment]
I think the appveyor build failed because it wanted to use NET 5.0 but the commit changes are just the version change to NET 6.0

**Comment by GioCirque** [comment]
Where does AppVeyor read the reps from? Can this be adjusted to use net6.0?

**Comment by jakubmisek** [comment]
PeachPie is fully compatible with WordPress on .NET 6.0 (as you can see on https://github.com/iolevel/wpdotnet-sdk/tree/master/app or https://github.com/iolevel/peachpie-wordpress/tree/master/app)

There is no need to change the .NET SDK to 6.0 unless you'd like to take advantage of .NET 6.0 right in the PeachPie codebase (in this repo source codes).

Also, your commit contains your NuGet packages ...

May I ask what is the point of this PR?

**Comment by jakubmisek** [comment]
add appveyor (https://ci.appveyor.com/project/dotnetfoundation/peachpie/build/messages): `NuGet package cannot be read: The required element 'authors' is missing`

**Comment by jakubmisek** [comment]
appveyor just builds the solution in the root of the project, using Visual Studio 2019 environment.

**Comment by jee-mj** [comment]
> PeachPie is fully compatible with WordPress on .NET 6.0 (as you can see on https://github.com/iolevel/wpdotnet-sdk/tree/master/app or https://github.com/iolevel/peachpie-wordpress/tree/master/app)
> 
> There is no need to change the .NET SDK to 6.0 unless you'd like to take advantage of .NET 6.0 right in the PeachPie codebase (in this repo source codes).
> 
> Also, your commit contains your NuGet packages ...
> 
> May I ask what is the point of this PR?

well .NET 6 was just a test using an LTS release of .NET.

It's mostly for testing purposes after the performance improvements touted in .NET 7.

**Comment by jakubmisek** [comment]
@jee-mj yep, but by changing the SDK version of the compiler you're only changing the **minimum** framework supported by PeachPie.

Just change the target framework of your executable app to net60/net70/net80/... and you'll get the performance improvements you want.

.nugs folder is supposed to be empty, see:
- https://github.com/peachpiecompiler/peachpie/blob/249048b45ac7ddf9557f44ca29626b1fa7df0b54/.gitignore#L144
- https://github.com/peachpiecompiler/peachpie/blob/master/.nugs/readme.md

**Pull request closed without merging**
