### PR TITLE
Feature/openssl

### PR DESCRIPTION
**Pull request by jakubmisek**
implements https://github.com/peachpiecompiler/peachpie/issues/402

### CODE REVIEW

**Comment by kripper** [comment]
How can openssl be included?
I tried adding:
  <ItemGroup>
	<PackageReference Include="Peachpie.Library.OpenSSL"/>
  </ItemGroup>

**Comment by jakubmisek** [comment]
it's referenced by default as a part of `Peachpie.Library`

**Comment by kripper** [comment]
We are using:
```
  <ItemGroup>
	<PackageReference Include="Peachpie.Library"/>
  </ItemGroup>
```
But we get: `warning PHP5006: Call to undefined function: 'openssl_sign'` with Version=0.9.981.0

**Comment by jakubmisek** [comment]
literally; just read my reply above

**Pull request merged**
