### PR TITLE
Fix debug message - wrong parameter order

### PR DESCRIPTION
**Pull request by andrew-demb**
Method signature - `public static void WriteLine (string format, params object?[] args);` (https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.debug.writeline?view=net-5.0#System_Diagnostics_Debug_WriteLine_System_String_System_Object___)

Inspired by https://habr.com/ru/company/pvs-studio/blog/573296#problemy-s-writeline

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/peachpiecompiler/peachpie?pullRequest=976) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/peachpiecompiler/peachpie?pullRequest=976) before we can accept your contribution.<br/><br/>:x: andrew-demb [sign now](https://cla.dotnetfoundation.org/peachpiecompiler/peachpie?pullRequest=976)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/peachpiecompiler/peachpie?pullRequest=976) it.</sub>

**Comment by jakubmisek** [comment]
I think the first argument was supposed to be a "source" of the message; originally there was a different trace API that expected that. In this case, "MAILER" should be omitted completely; it's not supposed to be outputed

**Comment by andrew-demb** [comment]
> I think the first argument was supposed to be a "source" of the message; originally there was a different trace API that expected that. In this case, "MAILER" should be omitted completely; it's not supposed to be outputed

I think you are right.
Fixed

**Comment by jakubmisek** [comment]
thank you!

**Comment by jakubmisek** [comment]
ref https://github.com/peachpiecompiler/peachpie/issues/977
ref https://pvs-studio.com/en/blog/posts/csharp/0855/

**Pull request merged**
