### PR TITLE
Add specifics SQL Server PDO constants

### LINKED ISSUE #813: PDO.SqlSrv does not includes specifics PDO constants
Hello,

I am trying to run our legacy app on PeachPie (sweet project by the way :smile:), and there are some issues.

When creating the PDO object, we pass some options, mainly:
```
$option = array( PDO::SQLSRV_ATTR_ENCODING => PDO::SQLSRV_ENCODING_SYSTEM );
```
And we are greeted with an exception: `System.InvalidOperationException : 'PDO::SQLSRV_ATTR_ENCODING could not be resolved.'`

It seems that the library `Peachpie.Library.PDO.SqlSrv` does not add the relevant constant specific to this driver.

See here: https://docs.microsoft.com/en-us/sql/connect/php/constants-microsoft-drivers-for-php-for-sql-server?view=sql-server-ver15#pdo_sqlsrv-driver-constants

I would have love to help with a PR, but I have no idea where to put these constants so PeachPie can make them available to the PHP code...

Thank you.

### PR DESCRIPTION
**Pull request by Indigo744**
Fixes #813 

I tried to follow the styles from SQLite and others, I hope it's ok 😸

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/peachpiecompiler/peachpie?pullRequest=819) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/peachpiecompiler/peachpie?pullRequest=819) before we can accept your contribution.<br/><br/>:x: Indigo744 [sign now](https://cla.dotnetfoundation.org/peachpiecompiler/peachpie?pullRequest=819)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/peachpiecompiler/peachpie?pullRequest=819) it.</sub>

**Comment by Indigo744** [comment]
As a side note, I was not able to find a proper documentation listing all constants and their respective values...

All docs simply use the name, but never the actual values:
https://www.php.net/manual/en/ref.pdo-sqlsrv.php
https://docs.microsoft.com/en-us/sql/connect/php/constants-microsoft-drivers-for-php-for-sql-server

So I simply used the PHP Intellisense of VSCode to print them all:
image

**Comment by jakubmisek** [comment]
Thanks, the constants looks alright.

--- 

We actually use PHP's reflection like `ReflectionClass` and `->getConstants()` to get the values from regular PHP. Sometimes we look into php's source code to understand where the constants come from...

**Comment by jakubmisek** [comment]
I guess now the constants need to be handled by PDO SqlSrv driver .. please feel free to create an issue for that.

**Pull request merged**
