### PR TITLE
reset resolved types from a previous compilation

### PR DESCRIPTION
**Pull request by crbrz**
Fix for #406

### CODE REVIEW

**Comment by jakubmisek** [comment]
thanks for the fix, it helped us to find the cause of the issue. This has to be fixed by making `BoundTypeRefFactory` an instance on `PhpCompilation` to allow compilations in parallel within a single process and better reuse of resolved symbols.

**Comment by jakubmisek** [comment]
fixed with https://github.com/peachpiecompiler/peachpie/commit/7ca861aca605aa8ec9c763963d718b32df4fbf51

thanks for the hint!

**Comment by crbrz** [comment]
I don't think msbuild/dotnet builds two different projects in a process at the same time but having `BoundTypeRefFactory` as an instance in `PhpCompilation` is definitely better.

**Comment by bfistein** [comment]
@crbrz are you on Twitter? If you are and agree, we'd love to give you a shout out publicly for your great contributions.

**Comment by crbrz** [comment]
No, I'm not using Twitter.

**Pull request closed without merging**
